# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nodepad < Formula
  desc "Nodepad — capture, resume, and bind from the terminal"
  homepage "https://inventlist.com/tools/nodepad"
  version "0.54.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.54.2/inventlist_Darwin_x86_64.tar.gz"
      sha256 "4387ac43c6e8b7c6342e5e7de93caf2c1d15566d4396d7d654fb04f3a76e58bc"

      define_method(:install) do
        # Installed AS `np`, not as a symlink beside another product's binary:
        # the flavor is chosen by argv[0], so the name IS the install.
        bin.install "inventlist" => "np"
        bin.install_symlink "np" => "nodepad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.54.2/inventlist_Darwin_arm64.tar.gz"
      sha256 "176bd062f02e96e2661223938543454578e4c177551370efa360d73179741fe1"

      define_method(:install) do
        # Installed AS `np`, not as a symlink beside another product's binary:
        # the flavor is chosen by argv[0], so the name IS the install.
        bin.install "inventlist" => "np"
        bin.install_symlink "np" => "nodepad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.54.2/inventlist_Linux_x86_64.tar.gz"
      sha256 "8a5fa1a005f109e0047e9ce62c2541118e8dbb91dc5a6dc76e8836ccd5b864f2"
      define_method(:install) do
        # Installed AS `np`, not as a symlink beside another product's binary:
        # the flavor is chosen by argv[0], so the name IS the install.
        bin.install "inventlist" => "np"
        bin.install_symlink "np" => "nodepad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.54.2/inventlist_Linux_arm64.tar.gz"
      sha256 "2ccf2b2647721a7c86bb21d31720dcdd5b342558c60f134afc72c686602ea04f"
      define_method(:install) do
        # Installed AS `np`, not as a symlink beside another product's binary:
        # the flavor is chosen by argv[0], so the name IS the install.
        bin.install "inventlist" => "np"
        bin.install_symlink "np" => "nodepad"
      end
    end
  end

  test do
    assert_match "nodepad #{version}", shell_output("#{bin}/np version")
  end
end
