# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nodepad < Formula
  desc "Nodepad — capture, resume, and bind from the terminal"
  homepage "https://inventlist.com/tools/nodepad"
  version "0.55.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.55.2/inventlist_Darwin_x86_64.tar.gz"
      sha256 "b913846fc5d988027b90927b9603126b487cd918653b7149fc98dc659fd57935"

      define_method(:install) do
        # Installed AS `np`, not as a symlink beside another product's binary:
        # the flavor is chosen by argv[0], so the name IS the install.
        bin.install "inventlist" => "np"
        bin.install_symlink "np" => "nodepad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.55.2/inventlist_Darwin_arm64.tar.gz"
      sha256 "0acf0f69d742394bdcc3321f504c942895a74816eaf5cd599d6e2f734ec51693"

      define_method(:install) do
        # Installed AS `np`, not as a symlink beside another product's binary:
        # the flavor is chosen by argv[0], so the name IS the install.
        bin.install "inventlist" => "np"
        bin.install_symlink "np" => "nodepad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.55.2/inventlist_Linux_x86_64.tar.gz"
      sha256 "52875467c3791f670f6cf37924a8769219517bc98f52a43caadbba5385e70c91"
      define_method(:install) do
        # Installed AS `np`, not as a symlink beside another product's binary:
        # the flavor is chosen by argv[0], so the name IS the install.
        bin.install "inventlist" => "np"
        bin.install_symlink "np" => "nodepad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.55.2/inventlist_Linux_arm64.tar.gz"
      sha256 "e0542a065854bfd4557b3177ebbf8181617cbfec0f618d2d082018dd564c7abe"
      define_method(:install) do
        # Installed AS `np`, not as a symlink beside another product's binary:
        # the flavor is chosen by argv[0], so the name IS the install.
        bin.install "inventlist" => "np"
        bin.install_symlink "np" => "nodepad"
      end
    end
  end

  test do
    assert_match "nodepad #{version}", shell_output("#{bin}/np version")
  end
end
