# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nodepad < Formula
  desc "Nodepad — capture, resume, and bind from the terminal"
  homepage "https://inventlist.com/tools/nodepad"
  version "0.55.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.55.0/inventlist_Darwin_x86_64.tar.gz"
      sha256 "9ef4bb16fd351fb9d69ae2fc6c9239c8056c3aa234551c81a14f03389a1e3289"

      define_method(:install) do
        # Installed AS `np`, not as a symlink beside another product's binary:
        # the flavor is chosen by argv[0], so the name IS the install.
        bin.install "inventlist" => "np"
        bin.install_symlink "np" => "nodepad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.55.0/inventlist_Darwin_arm64.tar.gz"
      sha256 "760c57dc6d33ca32ca39cbf5b778a36a762dd8341f5eb0709f3cc32abd3767d6"

      define_method(:install) do
        # Installed AS `np`, not as a symlink beside another product's binary:
        # the flavor is chosen by argv[0], so the name IS the install.
        bin.install "inventlist" => "np"
        bin.install_symlink "np" => "nodepad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.55.0/inventlist_Linux_x86_64.tar.gz"
      sha256 "e9ed8cae77235ad7956fb7699923d68546ea8dc4744f8e143b6b726cdd783cb3"
      define_method(:install) do
        # Installed AS `np`, not as a symlink beside another product's binary:
        # the flavor is chosen by argv[0], so the name IS the install.
        bin.install "inventlist" => "np"
        bin.install_symlink "np" => "nodepad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/inventlist/cli-releases/releases/download/v0.55.0/inventlist_Linux_arm64.tar.gz"
      sha256 "fce9a43d276a002a8aacd48b9203f93249239c6527019b679145c5ea7a21e772"
      define_method(:install) do
        # Installed AS `np`, not as a symlink beside another product's binary:
        # the flavor is chosen by argv[0], so the name IS the install.
        bin.install "inventlist" => "np"
        bin.install_symlink "np" => "nodepad"
      end
    end
  end

  test do
    assert_match "nodepad #{version}", shell_output("#{bin}/np version")
  end
end
